# Generated by Django 5.0.2 on 2024-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
