# Generated by Django 5.0.2 on 2024-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_categories_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
