# Generated by Django 5.0.2 on 2024-02-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='videos.tag'),
        ),
    ]
